### ISSUE TITLE
Use checkboxes where checkbox semantic is used

### ISSUE THREAD

**Issue by rku** [dl1ksv/linpsk#1]
Thanks for your work on LinPSK.

The program uses radio button style GUI elements where the semantic is actually that of a checkbox. This may confuse users. It would probably be a good idea to replace those elements with checkboxes and use radio buttons only where necessary (for example in the demo mode groupbox in the general settings dialog).

I can provide a patch via pull request for this, if you like.

**Comment by dl1ksv** [comment]
Thank you for your proposal, but I disagree.  Of course you can obtain the same results with checkboxes and it's no big deal to switch to checkboxes.
I looked for gui hints of using radiobuttons or checkboxes.
I found no real definition, but you use radiobuttons to switch one feature on or off or if you have a 1<->n selection. The demo mode button switches the demo mode on or off.
Checkboxes are mainly used for n<->m selections.
As users are used to see radiobuttons for more than 15 years, I think it's appropriate to keep the Radiobuttons.

**Comment by rku** [comment]
Thanks for your quick response. I have never seen radio buttons for boolean options before. So i was confused. I do agree with the view described [here](https://en.wikipedia.org/wiki/Radio_button)  for example, where a radio button is always within a group of two or more and is used to select one of the predefined options. However, it is your code and you are free to do whatever you like. :) I can live with the radio buttons.

**Comment by dl1ksv** [comment]
I think it's almost a philosophical question.
