### ISSUE TITLE
Use QT's QAudioDevice* classes for audio device management

### ISSUE THREAD

**Issue by rku** [dl1ksv/linpsk#2]
It would be nice if audio devices could be selected from a combobox instead of fiddling around with alsa device names. Why not use QT's QAudioDevice\* classes here? The LinPSK_{Play|Record} device names could still be handled as a special case.

If you are short of time, I can create a patch for this.

**Comment by dl1ksv** [comment]
You are right, a combobox would be appropriate. This is a good  proposal. But instead of using QAudioDeviceInfo I'll prefer to use the contents of /proc/asound/cards, as I already use it in csound.cpp.
I'll check.

**Comment by dl1ksv** [comment]
I just uploaded a new version. Could you please check, if it works for you ?
Thanks.

**Comment by rku** [comment]
Looks good. Thank you!
