### ISSUE TITLE
Build problem on macOS Big Sur

### ISSUE THREAD

**Issue by placentiusz** [dl1ksv/linpsk#5]
I try to build on Mac OS  ver. 11.2.1  but I have problems with:
1. In file included from ../gui/crxdisplay.cpp:21:
../src/csound.h:30:10: fatal error: 'alsa/asoundlib.h' file not found
#include <alsa/asoundlib.h>

Is available port for PortAudio? On old linpsk.sourceforge.net page I see DarwinPsk port but it stop on 0.8 version.

How to build DarwinPSK?

**Comment by dl1ksv** [comment]
linpsk does not build on Mac as it is based on alsa .
DarwinPSK was running on a Mac (ppc) and qt3 with the help of portaudio. Meanwhile qt has changed to qt5. I don't know if it would build on a modern Mac. As I have no longer access to a Mac, I can't check it.

Perhaps the short description of Tom Dove helps to try a build.
[Description of DarwinPSK](http://linpsk.sourceforge.net/darwinpskdoc_7.html)

Another psk31/rtty program for Mac OSX is cocoaModem by Kok Chen , W7AY, but I don't know if it's available for the latest Mac OSX.
